[project]
name = "agent-deployment"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "bedrock-agentcore>=1.1.1",
    "strands-agents-tools>=0.2.17",
    "strands-agents[gemini]>=1.19.0",
    "youtube-transcript-api>=1.2.3",
]
